export const GET_MOVIES_LIST = 'GET_MOVIES_LIST'
export const SET_MOVIES_LIST_LOADING = 'SET_MOVIES_LIST_LOADING'


export const ADD_TAG_LIST = 'ADD_TAG_LIST'
export const REMOVE_TAG_LIST = 'REMOVE_TAG_LIST'
export const SEARCH_TAG_LIST = 'SEARCH_TAG_LIST'